secrets:
  db_password_telegraf:
    file: ${SECRETS_DIR:-./secrets}/db_password_telegraf.txt
  mqtt_password_telegraf:
    file: ${SECRETS_DIR:-./secrets}/mqtt_password_telegraf.txt

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    restart: always
    mem_limit: "256M"
    ports:
      - "1883:1883"
    volumes:
      - ${CONFIG_DIR:-./mosquitto/config}/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ${CONFIG_DIR:-./mosquitto/config}/pwfile:/mosquitto/config/pwfile:ro
      - ${DATA_DIR:-./mosquitto/mosquitto_data}:/mosquitto/data
      - ${LOG_DIR:-./mosquitto/mosquitto_log}:/mosquitto/log
    security_opt:
      - no-new-privileges:true
  
  telegraf:
    container_name: telegraf
    image: telegraf:1.35
    restart: always
    depends_on:
      - mosquitto
      - timescaledb
    secrets:
      - db_password_telegraf
      - mqtt_password_telegraf
    volumes:
      - ${TELEGRAF_CONF:-./telegraf/telegraf.conf}:/etc/telegraf/telegraf.conf:ro
      - no-new-privileges:true

  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:2.25.0-pg17
    restart: always
    environment:
      POSTGRES_DB: sensors_db
      POSTGRES_USER: telegraf
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password_telegraf
    secrets:
      - db_password_telegraf
    volumes:
      - ${TS_DATA_DIR:-./timescaledb/data}:/var/lib/postgresql/data
      - ${TS_INIT_DIR:-./timescaledb/init}:/docker-entrypoint-initdb.d
    security_opt:
      - no-new-privileges:true

  grafana:
    container_name: grafana
    image: grafana/grafana:12.3.2
    restart: always
    user: "472:472"
    ports:
      - "3000:3000"
    volumes:
      - ${GRAFANA_DATA_DIR:-./grafana/data}:/var/lib/grafana
      - ${GRAFANA_PROV_DIR:-./grafana/provisioning}:/etc/grafana/provisioning
    security_opt:
      - no-new-privileges:true
